apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-a
  labels:
    app: svc-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-a
  template:
    metadata:
      labels:
        app: svc-a
    spec:
      containers:
        - name: svc-a
          image: dakshsawhneyy/demo-service-a:e8476e7638613e27ee932f6de5b792e09d0bf6d3
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: "100m" # Request 1/10th of a CPU core
              memory: "128Mi" # Request 128 Mebibytes of memory
          env:
          - name: SERVICE_B_URI
            value: "http://svc-b-service:9001"