apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: svc-b-hpa
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc-b
  minReplicas: 2
  maxReplicas: 4
  # scale up if the average CPU usage across all pods goes above 70% of their requested amount.
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70